version: '3.9'

services:
  db-aptekaplus:
    image: postgres:15-alpine
    restart: always
    container_name: db-aptekaplus
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=aptekaplus'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    command: -p 5432
    volumes:
      - data-aptekaplus:/var/lib/postgresql/data


volumes:
  data-aptekaplus: