version: '3.9'

services:
  app:
    build: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-aptekaplus:5432/aptekaplus
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - "8080"

  db-aptekaplus:
    image: postgres:15-alpine
    restart: always
    container_name: db-aptekaplus
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=aptekaplus'
      - 'POSTGRES_PASSWORD=123'
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    command: -p 5432
    volumes:
      - data-aptekaplus:/var/lib/postgresql/data



volumes:
  data-aptekaplus:
